name: Draft release

on:
  push:
  repository_dispatch:
    types: [draft-release]

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Decrypt secrets
        run: |
          yarn env test
          cat .env | grep -v \# | xargs -I %s echo %s >> $GITHUB_ENV
        env:
          ENV_PASSPHRASE: ${{ secrets.ENV_PASSPHRASE }}
      - run: yarn --frozen-lockfile
      - name: Determine version type
        id: type
        run: echo "::set-output name=type::$(yarn --silent conventional-recommended-bump -p angular)"
      - name: Set version
        id: version
        run: echo "::set-output name=version::$(npm version --no-git-tag-version ${{ steps.type.outputs.type }})"
      - name: Generate changelog
        # cspell:word versionrc slackapi
        run: |
          yarn --silent conventional-changelog -n .versionrc.json -i CHANGELOG.md -s
          yarn --silent conventional-changelog -n .versionrc.json -o RELEASE_NOTES.md
      - name: Format changelog
        run: yarn --silent prettier -w CHANGELOG.md RELEASE_NOTES.md
      - name: Commit and tag
        run: |
          git config --global user.name 'Showcase IDX Bot'
          git config --global user.email 'robot@showcaseidx.com'
          git add package.json CHANGELOG.md
          git commit -m "chore(release): ${{ steps.version.outputs.version }}"
          git tag -a "${{ steps.version.outputs.version }}" -m "${{ steps.version.outputs.version }}"
          git push --follow-tags -u origin HEAD
      - name: Release
        run: gh release create ${{ steps.version.outputs.version }} -F RELEASE_NOTES.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
